spring:
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  #datasource:
    #url: jdbc:h2:mem:testdb
    #driver-class-name: org.h2.Driver
    #username: sa
    #password: password